'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowLeft, LogOut, Inbox, LockKeyhole, RefreshCw } from 'lucide-react';

type Quote={id:string;name:string;email:string;phone?:string;type?:string;message:string;status:string;note?:string;created_at:string};
export default function Admin(){
 const [logged,setLogged]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[quotes,setQuotes]=useState<Quote[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
 async function load(){setLoading(true);const r=await fetch('/api/admin/quotes');if(r.status===401){setLogged(false);setLoading(false);return}const j=await r.json();if(!r.ok){setError(j.error||'Teklifler alınamadı.')}else{setLogged(true);setQuotes(j.data||[])}setLoading(false)}
 useEffect(()=>{load()},[]);
 async function login(e:React.FormEvent){e.preventDefault();setError('');const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(!r.ok){setError('Yönetici e-postası veya şifre hatalı.');return}setPassword('');load()}
 async function update(id:string, status:string, note:string){await fetch('/api/admin/quotes',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status,note})});load()}
 async function logout(){await fetch('/api/admin/logout',{method:'POST'});setLogged(false);setQuotes([])}
 if(!logged)return <main className="admin-page"><div className="admin-login"><Link href="/" className="seo-brand"><span>J</span> JOKER <b>ADMIN</b></Link><div className="admin-login-card"><LockKeyhole/><span className="seo-eyebrow">PRIVATE CONTROL CENTER</span><h1>Yönetim <span>girişi.</span></h1><p>Bu alan yalnızca yetkili JOKER YAZILIM yöneticisi içindir.</p><form onSubmit={login}><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Yönetici e-postası" autoComplete="username" required/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Yönetici şifresi" autoComplete="current-password" required/><button className="seo-cta">Güvenli giriş</button></form>{error&&<div className="form-result error">{error}</div>}<small>Tek yönetici hesabı. ADMIN_EMAIL + ADMIN_PASSWORD + ADMIN_SESSION_SECRET Vercel Environment Variables üzerinden tanımlanır.</small></div></div></main>;
 return <main className="admin-page"><header className="admin-top"><Link href="/" className="seo-brand"><span>J</span> JOKER <b>ADMIN</b></Link><div className="admin-actions"><button onClick={load} aria-label="Yenile"><RefreshCw size={15}/></button><button onClick={logout}><LogOut size={15}/> Çıkış</button><Link href="/"><ArrowLeft size={15}/> Siteye dön</Link></div></header><section className="admin-main"><span className="seo-eyebrow">JOKER / PRIVATE CONTROL CENTER</span><h1>Teklif <span>merkezi.</span></h1><div className="admin-stats"><div><small>TOPLAM TEKLİF</small><b>{quotes.length}</b><span>Kayıtlı talepler</span></div><div><small>YENİ</small><b>{quotes.filter(q=>q.status==='Yeni').length}</b><span>Bekleyen</span></div><div><small>İNCELENİYOR</small><b>{quotes.filter(q=>q.status==='İnceleniyor').length}</b><span>Aktif</span></div><div><small>TAMAMLANDI</small><b>{quotes.filter(q=>q.status==='Tamamlandı').length}</b><span>Sonuçlanan</span></div></div><div className="admin-panel"><div className="admin-panel-head"><h2><Inbox size={18}/> Gelen teklifler</h2><span>{loading?'Yükleniyor…':'Son 100 kayıt'}</span></div>{error&&<p className="form-result error">{error}</p>}{!quotes.length&&!loading?<p>Henüz teklif kaydı yok. Veritabanı bağlantısını kontrol edin.</p>:<div className="quote-table">{quotes.map(q=><article key={q.id} className="quote-row"><div><small>{new Date(q.created_at).toLocaleString('tr-TR')}</small><h3>{q.name}</h3><a href={`mailto:${q.email}`}>{q.email}</a>{q.phone&&<a href={`tel:${q.phone}`}>{q.phone}</a>}</div><div><b>{q.type||'Genel'}</b><p>{q.message}</p>{q.note&&<em>Not: {q.note}</em>}</div><div><select value={q.status} onChange={e=>update(q.id,e.target.value,q.note||'')}><option>Yeni</option><option>İnceleniyor</option><option>Teklif Gönderildi</option><option>Tamamlandı</option><option>İptal</option></select><textarea defaultValue={q.note||''} placeholder="İç not" onBlur={e=>{if(e.target.value!==q.note)update(q.id,q.status,e.target.value)}}/></div></article>)}</div>}</div></section></main>;
}
