export type Service = {
  slug: string;
  title: string;
  short: string;
  description: string;
  bullets: string[];
  keywords: string[];
};

export const servicePages: Service[] = [
  { slug: 'web-yazilim', title: 'Web Yazılım', short: 'Modern web siteleri, SaaS ürünleri ve özel web uygulamaları.', description: 'JOKER YAZILIM; işletmeler için hızlı, responsive, SEO odaklı ve ölçeklenebilir web yazılımları geliştirir. Kurumsal web sitelerinden yönetim panellerine kadar ihtiyaç duyulan yapıyı uçtan uca planlarız.', bullets: ['Next.js / React tabanlı modern arayüzler', 'Responsive ve erişilebilir tasarım', 'SEO ve performans odaklı altyapı', 'Admin paneli ve API entegrasyonları'], keywords: ['web yazılım', 'web uygulama', 'kurumsal web yazılım', 'Yalova web yazılım'] },
  { slug: 'mobil-uygulama', title: 'Mobil Uygulama', short: 'Android ve iOS için kullanıcı odaklı mobil uygulamalar.', description: 'Fikrinizi mobil deneyime dönüştürüyoruz. Kullanıcı akışlarını, API bağlantılarını, bildirimleri ve yayın sürecini birlikte planlayarak sürdürülebilir mobil ürünler geliştiriyoruz.', bullets: ['Android ve iOS deneyimi', 'Modern UI/UX', 'REST API ve servis entegrasyonları', 'Yayın ve bakım desteği'], keywords: ['mobil uygulama geliştirme', 'android uygulama', 'ios uygulama', 'mobil yazılım'] },
  { slug: 'e-ticaret-yazilimi', title: 'E-Ticaret Yazılımı', short: 'Ürün, sipariş, ödeme, stok ve müşteri süreçlerini yöneten sistemler.', description: 'Satış operasyonunuzu tek merkezde yönetebileceğiniz e-ticaret çözümleri tasarlıyoruz. Mağaza arayüzü ile yönetim tarafını aynı ürün deneyiminde buluşturuyoruz.', bullets: ['Ürün ve stok yönetimi', 'Sipariş ve ödeme akışları', 'Müşteri ve kampanya yönetimi', 'Raporlama ve entegrasyonlar'], keywords: ['e-ticaret yazılımı', 'e-ticaret sitesi', 'online mağaza yazılımı', 'e-ticaret otomasyonu'] },
  { slug: 'ozel-yazilim', title: 'Özel Yazılım', short: 'Hazır paketlere sığmayan işler için işletmeye özel sistemler.', description: 'İş modelinize göre sıfırdan özel yazılım geliştiriyoruz. Kullanıcı rolleri, modüller, iş akışları, veri yapısı ve entegrasyonlar proje ihtiyaçlarına göre şekillenir.', bullets: ['İhtiyaca özel modüler mimari', 'Rol ve yetkilendirme sistemleri', 'Özel iş akışları', 'Uzun vadeli bakım ve geliştirme'], keywords: ['özel yazılım', 'özel yazılım geliştirme', 'kurumsal özel yazılım', 'işletme yazılımı'] },
  { slug: 'yapay-zeka', title: 'Yapay Zekâ & AI', short: 'AI entegrasyonları, veri analizi ve akıllı iş akışları.', description: 'Yapay zekâyı işin gerçek ihtiyacına bağlayan çözümler geliştiriyoruz. Veri işleme, tahmin, metin analizi ve AI destekli otomasyon senaryolarını ürününüze entegre ediyoruz.', bullets: ['AI API entegrasyonları', 'Makine öğrenmesi senaryoları', 'Veri analizi ve tahmin', 'Akıllı kullanıcı deneyimleri'], keywords: ['yapay zeka yazılımı', 'AI entegrasyonu', 'makine öğrenmesi', 'AI otomasyon'] },
  { slug: 'otomasyon', title: 'Otomasyon', short: 'Tekrarlayan operasyonları azaltan akıllı iş akışları.', description: 'Manuel olarak tekrarlanan süreçleri analiz edip dijital iş akışlarına dönüştürüyoruz. Bildirim, veri aktarımı, raporlama ve servisler arası otomasyonlar tasarlıyoruz.', bullets: ['İş akışı otomasyonu', 'Bildirim ve görev sistemleri', 'Raporlama otomasyonu', 'Webhook ve API bağlantıları'], keywords: ['iş otomasyonu', 'yazılım otomasyonu', 'iş süreçleri otomasyonu', 'otomasyon yazılımı'] },
  { slug: 'api-entegrasyon', title: 'API & Entegrasyon', short: 'Farklı servisleri güvenli ve izlenebilir API katmanında buluşturun.', description: 'Ödeme, CRM, ERP, kargo, mesajlaşma ve diğer üçüncü taraf servisleri projenizin mimarisine uygun şekilde entegre ediyoruz.', bullets: ['REST API tasarımı', 'Webhook sistemleri', 'Üçüncü taraf servis entegrasyonları', 'Kimlik doğrulama ve hata yönetimi'], keywords: ['API entegrasyonu', 'REST API', 'web servis entegrasyonu', 'yazılım entegrasyonu'] },
  { slug: 'kurumsal-yazilim', title: 'Kurumsal Yazılım', short: 'Şirket içi süreçleri tek merkezde yöneten dijital sistemler.', description: 'Kurumsal operasyonları sadeleştiren kullanıcı, görev, müşteri, stok, rapor ve yetkilendirme modüllerini işletmeye özel bir sistemde birleştiriyoruz.', bullets: ['Kullanıcı ve rol yönetimi', 'Dashboard ve raporlama', 'Departman bazlı iş akışları', 'Veri ve güvenlik altyapısı'], keywords: ['kurumsal yazılım', 'şirket içi yazılım', 'kurumsal otomasyon', 'işletme yönetim sistemi'] },
];

export const blogPosts = [
  { slug: 'ozel-yazilim-mi-hazir-yazilim-mi', title: 'Özel yazılım mı, hazır yazılım mı?', category: 'Yazılım', excerpt: 'İşletmenizin ihtiyaçlarına göre iki yaklaşımın maliyet, esneklik, bakım ve ölçeklenebilirlik açısından farklarını nasıl değerlendirebileceğinizi anlatıyoruz.', date: '2026-09-08', read: '6 dk', body: ['Her işletmenin süreçleri aynı değildir. Hazır yazılım hızlı başlangıç sağlayabilir; ancak süreçleriniz farklılaştıkça özel geliştirme ihtiyacı ortaya çıkabilir.', 'Özel yazılım yaklaşımında önce problem ve kapsam belirlenir, ardından mimari ve teknoloji seçilir. Böylece yalnızca gerçekten ihtiyaç duyulan modüller geliştirilir.', 'Karar verirken lisans maliyetinin yanında entegrasyon, bakım, veri sahipliği, kullanıcı sayısı ve gelecekteki geliştirme ihtiyacını da birlikte değerlendirmek gerekir.'] },
  { slug: 'seo-uyumlu-web-sitesi-nasil-yapilir', title: 'SEO uyumlu web sitesi nasıl yapılır?', category: 'SEO', excerpt: 'Teknik SEO, içerik mimarisi, hız, mobil deneyim ve yapılandırılmış veriyi aynı sistemde ele alan pratik bir yaklaşım.', date: '2026-09-08', read: '7 dk', body: ['SEO yalnızca anahtar kelimeleri sayfaya eklemek değildir. Arama motorlarının sayfaları keşfetmesi, anlamlandırması ve kullanıcıya hızlı sunması gerekir.', 'Sağlam bir yapı; doğru başlık hiyerarşisi, açıklayıcı içerik, canonical URL, sitemap, robots kuralları, yapılandırılmış veri ve güçlü mobil deneyimi kapsar.', 'Bunun yanında Search Console verileriyle hangi sorguların trafik getirdiği takip edilerek içerik ve sayfa mimarisi sürekli geliştirilebilir.'] },
  { slug: 'isletmeler-icin-yapay-zeka', title: 'İşletmeler yapay zekâyı nerede kullanabilir?', category: 'AI', excerpt: 'AI teknolojisini gerçek iş akışlarına bağlamak için müşteri hizmetlerinden raporlamaya kadar örnek kullanım alanları.', date: '2026-09-08', read: '5 dk', body: ['Yapay zekâ tek başına bir ürün değildir; doğru probleme bağlandığında iş akışının bir parçası olur.', 'Belge sınıflandırma, metin özetleme, müşteri mesajlarını önceliklendirme, rapor hazırlama ve veri analizi gibi süreçler otomasyona uygun adaylar olabilir.', 'En doğru başlangıç, zaman kaybettiren tekrarlı bir işi seçmek ve ölçülebilir bir pilot senaryo oluşturmaktır.'] },
  { slug: 'web-sitesi-fiyati-nasil-belirlenir', title: 'Web sitesi ve yazılım fiyatı nasıl belirlenir?', category: 'Rehber', excerpt: 'Yazılım tekliflerinde fiyatı etkileyen ekran, kullanıcı, entegrasyon, içerik, güvenlik ve bakım kalemlerini açıklıyoruz.', date: '2026-09-08', read: '6 dk', body: ['Bir yazılım projesinin fiyatı yalnızca sayfa sayısıyla belirlenmez. Kullanıcı rolleri, özel iş kuralları, entegrasyonlar, veri yapısı ve yönetim paneli gibi detaylar kapsamı değiştirir.', 'Teklif öncesinde hedef, kapsam, teslim planı ve bakım ihtiyacını netleştirmek hem müşteri hem geliştirme ekibi için daha sağlıklı bir süreç oluşturur.', 'JOKER YAZILIM olarak hazır paket yerine ihtiyaca göre kapsam çıkarıp uygun bütçeli bir yol haritası hazırlamayı hedefliyoruz.'] },
];

export type CaseStudy = { slug:string; title:string; category:string; status:string; summary:string; problem:string; solution:string; tech:string[]; architecture:string[]; notes:string[] };
export const caseStudies: CaseStudy[] = [
 {slug:'saglik-analiz-platformu',title:'Sağlık Analiz Platformu',category:'Web / AI',status:'Öne çıkan çalışma',summary:'React.js ve Flask ile geliştirilen, makine öğrenmesi modellerini kullanıcı dostu bir dashboard deneyimiyle birleştiren proje.',problem:'Kullanıcıların model çıktılarından anlamlı bir analiz ekranına hızlı şekilde ulaşabilmesi ve farklı risk senaryolarının tek deneyimde sunulması hedeflendi.',solution:'React tabanlı arayüz, Flask API katmanı ve Python tabanlı model akışları birbirinden ayrılarak daha yönetilebilir bir yapı kurgulandı.',tech:['React.js','Flask','Python','Machine Learning'],architecture:['React UI','Flask REST API','Python / ML','Data layer'],notes:['Bu proje sağlık hizmeti veya tıbbi teşhis iddiası olarak sunulmamaktadır.','Gösterilen sonuçlar ve model davranışları proje kapsamındaki teknik çalışmayı ifade eder.']},
 {slug:'gida-deposu-websitesi',title:'Gıda Deposu Websitesi',category:'Web',status:'Gerçek çalışma',summary:'Gıda deposu markası için hazırlanan gerçek web sitesi çalışması.',problem:'Markanın ürün ve kurumsal iletişim ihtiyaçlarını modern ve mobil uyumlu bir web deneyiminde toplamak.',solution:'Responsive web arayüzü, hizmet/ürün sunumu ve hızlı iletişim odaklı yapı.',tech:['Web Design','Responsive UI','SEO','Frontend'],architecture:['Responsive UI','Content structure','Conversion flow'],notes:['Bu çalışma gerçek proje videosu ile portföye eklenmiştir.']},
 {slug:'cilingir-websitesi',title:'Çilingir Websitesi',category:'Web',status:'Gerçek çalışma',summary:'Çilingir hizmetleri için hazırlanan gerçek web sitesi; hızlı iletişim ve mobil dönüşüm odaklı yapı.',problem:'Acil hizmet arayan ziyaretçinin doğru hizmete hızlı ulaşmasını ve iletişim kurmasını sağlamak.',solution:'Mobil öncelikli hizmet sunumu, güçlü iletişim CTA’ları ve yerel görünürlük odaklı yapı.',tech:['Web Design','Responsive UI','Local SEO','Conversion'],architecture:['Mobile-first UI','CTA flow','Service structure'],notes:['Bu çalışma gerçek proje videosu ile portföye eklenmiştir.']},
 {slug:'kafe-websitesi',title:'Kafe Websitesi',category:'Web',status:'Gerçek çalışma',summary:'Kafe işletmesi için hazırlanan gerçek web sitesi çalışması; marka sunumu ve ziyaretçi deneyimini öne çıkarıyor.',problem:'Kafenin marka kimliğini ve ziyaretçi için gerekli bilgileri modern bir dijital deneyimde sunmak.',solution:'Görsel odaklı responsive arayüz ve kullanıcıyı bilgi/iletişim aksiyonlarına yönlendiren sayfa yapısı.',tech:['Web Design','Responsive UI','Frontend','UX'],architecture:['Responsive layout','Visual hierarchy','UX flow'],notes:['Bu çalışma gerçek proje videosu ile portföye eklenmiştir.']},
 {slug:'aydogan-canta',title:'Aydoğan Çanta',category:'Web / E-Ticaret',status:'Yayındaki gerçek proje',summary:'Çanta imalatı markası için yayında olan gerçek web sitesi.',problem:'Üretim, ürünler, toplu sipariş ve müşteri iletişimini tek dijital deneyimde sunmak.',solution:'Kurumsal marka sunumu ile ürün/mağaza ve teklif iletişimini bir araya getiren yayındaki web yapısı.',tech:['Web Development','E-Commerce','Responsive UI','SEO'],architecture:['Responsive web','Product presentation','Conversion flow'],notes:['Canlı proje: https://aydogancanta.com/']},
 {slug:'modern-dashboard-interfaces',title:'Modern Dashboard Interfaces',category:'Web / UI',status:'Öne çıkan çalışma',summary:'React ve Next.js ile modern dashboard arayüzleri; veri yoğun ekranları daha sade ve kullanılabilir hale getirmek için tasarlandı.',problem:'Yoğun veri içeren yönetim ekranlarında bilgi hiyerarşisini güçlendirmek ve farklı ekran boyutlarında tutarlı bir deneyim sağlamak.',solution:'Component tabanlı UI yaklaşımı, responsive grid yapısı ve tekrar kullanılabilir dashboard bileşenleriyle arayüz sistemi oluşturuldu.',tech:['React','Next.js','UI/UX','Dashboard'],architecture:['Design system','Reusable components','Responsive layout','Frontend state'],notes:['Bu çalışma arayüz ve frontend geliştirme yetkinliğini göstermek için öne çıkarılmıştır.']},
 {slug:'kurumsal-web-platformu',title:'Kurumsal Web Platformu',category:'Web',status:'Örnek çözüm',summary:'Kurumsal firmaların hizmet, içerik, ekip ve iletişim süreçlerini tek dijital deneyimde birleştiren çözüm konsepti.',problem:'Farklı içerik ve iletişim ihtiyaçlarını hızlı, SEO uyumlu ve yönetilebilir bir kurumsal yapıda toplamak.',solution:'Next.js tabanlı sayfa mimarisi, CMS/API bağlantıları ve performans odaklı frontend yapısı planlandı.',tech:['Next.js','TypeScript','SEO','CMS'],architecture:['Next.js','Content API','SEO layer','CDN'],notes:['Bu çalışma örnek çözüm vitrini olarak sunulmaktadır; gerçek müşteri projesi değildir.']},
 {slug:'e-ticaret-operasyon-merkezi',title:'E-Ticaret Operasyon Merkezi',category:'E-Ticaret',status:'Örnek çözüm',summary:'Ürün, stok, sipariş, ödeme ve müşteri süreçlerini merkezi bir yönetim deneyiminde birleştiren çözüm konsepti.',problem:'Satış operasyonlarını farklı araçlar arasında bölmek yerine tek merkezden takip edilebilir hale getirmek.',solution:'Mağaza frontend’i, backend servisleri ve ödeme/veri katmanlarının API üzerinden ayrıştırıldığı ölçeklenebilir mimari.',tech:['React','Node.js','SQL','Payment API'],architecture:['Storefront','API layer','Database','Payment provider'],notes:['Bu çalışma örnek çözüm vitrini olarak sunulmaktadır; gerçek müşteri projesi değildir.']}
];
