import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowRight, CheckCircle2 } from 'lucide-react';
import { servicePages } from '../../content';

export function generateStaticParams(){ return servicePages.map(s=>({slug:s.slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{ const {slug}=await params; const s=servicePages.find(x=>x.slug===slug); if(!s) return {}; return {title:`${s.title} | JOKER YAZILIM`,description:s.description,keywords:s.keywords,alternates:{canonical:`/hizmetler/${s.slug}`},openGraph:{title:`${s.title} | JOKER YAZILIM`,description:s.description,type:'website'}}; }
export default async function ServiceDetail({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const s=servicePages.find(x=>x.slug===slug); if(!s) notFound(); const jsonLd={'@context':'https://schema.org','@type':'Service',name:s.title,provider:{'@type':'Organization',name:'JOKER YAZILIM'},description:s.description,areaServed:'Türkiye'}; return <main className="seo-page"><header className="seo-nav"><Link href="/" className="seo-brand"><span>J</span> JOKER <b>YAZILIM</b></Link><Link href="/#iletisim" className="seo-cta">Ücretsiz Teklif <ArrowRight size={15}/></Link></header><div className="seo-wrap detail"><Link href="/hizmetler" className="back-link"><ArrowLeft size={15}/> Tüm hizmetler</Link><span className="seo-eyebrow">JOKER / {s.title.toUpperCase()}</span><h1>{s.title}<span>.</span></h1><p className="seo-lead">{s.description}</p><div className="detail-layout"><section className="detail-main"><h2>Bu hizmette neler yapıyoruz?</h2><div className="check-list">{s.bullets.map(x=><div key={x}><CheckCircle2 size={18}/><span>{x}</span></div>)}</div><h2>Neden JOKER YAZILIM?</h2><p>İhtiyaç, bütçe ve hedefleri birlikte değerlendirerek gereksiz özellikleri azaltıyor; performans, güvenlik, mobil uyumluluk, SEO ve sürdürülebilirliği baştan planlıyoruz.</p><p>Proje kapsamı netleştikten sonra teknoloji seçimi, tasarım, geliştirme, test, yayın ve yayın sonrası destek adımlarını kontrollü biçimde ilerletiyoruz.</p></section><aside className="detail-side"><small>PROJENİZ İÇİN</small><strong>Doğru teknoloji<br/>ile başlayalım.</strong><p>Fikrinizi birkaç cümleyle anlatın; uygun kapsam ve bütçe için ön değerlendirme yapalım.</p><Link href="/#iletisim" className="seo-cta wide">Teklif Al <ArrowRight size={16}/></Link></aside></div></div><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/></main> }
